# Generated by Django 4.2.9 on 2024-08-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BtpApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="imgmodel",
            name="image",
            field=models.ImageField(upload_to="dams"),
        ),
    ]
